import './style.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navigation from "./Navigation"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  pageMetadata,
}: {
  children: React.ReactNode,
  pageMetadata: Metadata,
}) {
  return (
    <html lang="en">
      <head>
        <title>{pageMetadata.title}</title>
        <meta name="description" content={pageMetadata.description} />
        {/* Add more meta tags as needed */}
      </head>
      <body className="home">
        <section className="section--bg section--bg-grey-gradient">
          <Navigation />
        </section>
        {children}
      </body>
    </html>
  )
}