import type { Metadata } from "next";

import Sidebar from "../components/Sidebar";
import Header from "../components/Header";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://webpersonify-cdn.s3.amazonaws.com/static/themes/keen/assets/css/demo1/pages/custom/general/user/login-v1.css"
          rel="stylesheet"
          type="text/css"
        />

        <link
          href="https://webpersonify-cdn.s3.amazonaws.com/static/themes/keen/assets/vendors/global/vendors.bundle.css"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="https://webpersonify-cdn.s3.amazonaws.com/static/themes/keen/assets/css/demo1/style.bundle.css"
          rel="stylesheet"
          type="text/css"
        />

        <link
          href="https://webpersonify-cdn.s3.amazonaws.com/static/themes/keen/assets/css/demo1/skins/header/base/light.css"
          rel="stylesheet"
          type="text/css"
        />

        <link
          href="https://webpersonify-cdn.s3.amazonaws.com/static/themes/keen/assets/css/demo1/skins/aside/navy.css"
          rel="stylesheet"
          type="text/css"
        />
      </head>
      <body>
        <div className="kt-grid kt-grid--root">
          <div className="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--ver">
            {/* Sidebar component */}
            <Sidebar />
            <div className="kt-grid__item kt-grid__item--fluid kt-wrapper">
              {/* Header component */}
              <Header />
              {/* Main content - dynamic children from the page */}
              <p> main layout called </p>
              <main>{children}</main>
              {/* Footer component */}

              <Footer />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
